services:
    db:
        image: postgres
        container_name: wilders_db
        environment:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_USER: "${DB_USER}"
            POSTGRES_DB: "${DB_NAME}"
        ports:
            - "5432:5432"
        volumes:
            - ./data/postgres:/data/postgres
        restart: unless-stopped
    api:
        build: ./
        container_name: wilders_api
        restart: unless-stopped
        ports:
            - "5000:5000"
        depends_on:
            - db
        command: pnpm run start
        volumes:
            - ./src:/api/src
    adminer:
        image: adminer
        container_name: wilders_adminer
        ports:
            - "8080:8080"
        depends_on:
            - db
        restart: unless-stopped
        volumes:
            - ./data/adminer:/data/adminer
